using System.Globalization;
using System.Text.RegularExpressions;

namespace Harness.MirrorView;

/// <summary>
/// Builds the register map out of two committed IR artifacts, and <b>refuses rather than guessing</b>.
///
/// <list type="bullet">
/// <item><b>The area pointer</b> — <c>MB_HOLD_REG := P#M&lt;base&gt;.0 WORD n</c> in the Modbus server
/// block. It gives the base byte and the declared width, which is what turns a <c>%M</c> address into a
/// register index.</item>
/// <item><b>The tag table</b> — <c>HarnessMirror.ir</c>. Name, type, address and the descriptive
/// <c>COMMENT</c> per tag.</item>
/// </list>
///
/// <para><b>Two files, not one, and they check each other.</b> Every tag must land inside the declared
/// area, no two tags may overlap, and each tag's address form must agree with its type name. A map that
/// fails any of those is refused with the offending line — because the alternative is a screen full of
/// plausible numbers against the wrong addresses.</para>
///
/// <para><b>The register arithmetic is the inverse of <c>Harness.Map.MirrorGeometry</c>'s</b>, which is
/// the class the copy layer's own addresses were generated by. That is deliberate: the check that this
/// parser places tags where the generator put them is a round-trip against an authority OUTSIDE this
/// file (see <c>MirrorMapParserTests.EveryTag_RoundTripsThroughMirrorGeometry</c>), not a restatement of
/// this file's own belief.</para>
/// </summary>
public static class MirrorMapParser
{
    // NAME UID : Type @ %ADDR <attributes...> COMMENT "text"
    private static readonly Regex TagLine = new(
        @"^\s*(?<name>[A-Za-z_][A-Za-z0-9_]*)\s+(?<uid>[0-9A-Fa-f]+)\s*:\s*(?<type>[A-Za-z_][A-Za-z0-9_]*)\s*@\s*(?<addr>%[A-Za-z]+[0-9]+(\.[0-9]+)?)(?<rest>.*)$",
        RegexOptions.Compiled | RegexOptions.CultureInvariant);

    // MB_HOLD_REG := P#M1000.0 WORD 37
    private static readonly Regex AreaPointer = new(
        @"P#M(?<base>[0-9]+)\.0\s+WORD\s+(?<count>[0-9]+)",
        RegexOptions.Compiled | RegexOptions.CultureInvariant);

    private static readonly Regex Address = new(
        @"^%M(?<kind>[DW]?)(?<byte>[0-9]+)(\.(?<bit>[0-9]+))?$",
        RegexOptions.Compiled | RegexOptions.CultureInvariant);

    /// <summary>Read both artifacts off disk and build the map. Any I/O failure is a refusal, not a throw.</summary>
    public static MirrorMapLoad Load(string tagTablePath, string areaPointerPath)
    {
        ArgumentNullException.ThrowIfNull(tagTablePath);
        ArgumentNullException.ThrowIfNull(areaPointerPath);

        string tagText;
        string areaText;

        try
        {
            tagText = File.ReadAllText(tagTablePath);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or ArgumentException)
        {
            return MirrorMapLoad.Refused(
                $"the mirror tag table '{tagTablePath}' could not be read: {ex.Message}. " +
                "There is no built-in map to fall back to, and inventing one is how a view comes to show " +
                "the right-looking numbers against the wrong addresses.");
        }

        try
        {
            areaText = File.ReadAllText(areaPointerPath);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or ArgumentException)
        {
            return MirrorMapLoad.Refused(
                $"the Modbus server block '{areaPointerPath}' could not be read: {ex.Message}. " +
                "It carries the MB_HOLD_REG area pointer, which is the only thing that turns a %M address " +
                "into a register index.");
        }

        return Parse(tagText, areaText, tagTablePath, areaPointerPath);
    }

    /// <summary>The whole parse, over text rather than paths, so every refusal is testable with no files.</summary>
    public static MirrorMapLoad Parse(string tagTableText, string areaPointerText, string tagTableSource, string areaPointerSource)
    {
        ArgumentNullException.ThrowIfNull(tagTableText);
        ArgumentNullException.ThrowIfNull(areaPointerText);

        var refusals = new List<string>();

        // ---- 1. THE AREA POINTER ----
        var pointerMatches = AreaPointer.Matches(areaPointerText);
        var pointers = pointerMatches
            .Select(m => (Base: int.Parse(m.Groups["base"].Value, CultureInfo.InvariantCulture),
                          Count: int.Parse(m.Groups["count"].Value, CultureInfo.InvariantCulture)))
            .Distinct()
            .ToList();

        if (pointers.Count == 0)
        {
            return MirrorMapLoad.Refused(
                $"no MB_HOLD_REG area pointer of the form 'P#M<base>.0 WORD <n>' was found in " +
                $"'{areaPointerSource}'. Without it there is no base byte, and a %M address cannot be " +
                "placed on the register grid at all.");
        }

        if (pointers.Count > 1)
        {
            return MirrorMapLoad.Refused(
                $"'{areaPointerSource}' carries {pointers.Count} DIFFERENT area pointers " +
                $"({string.Join(", ", pointers.Select(p => $"P#M{p.Base}.0 WORD {p.Count}"))}). " +
                "Which one the server actually uses is not decidable from here, and picking the first " +
                "would produce a whole map against a base nobody stated.");
        }

        var (baseByte, declared) = pointers[0];

        if (baseByte % 2 != 0)
        {
            refusals.Add($"the area pointer's base %M{baseByte} is not word-aligned. Holding register r " +
                         "is the word at base + 2r, so an odd base straddles every register.");
        }

        if (declared < 1)
            refusals.Add($"the area pointer declares WORD {declared} — an area with no registers.");

        if (refusals.Count > 0) return MirrorMapLoad.Refused(refusals);

        // ---- 2. THE TAGS ----
        var lines = tagTableText.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n');
        var inTags = false;
        var tags = new List<MirrorTag>();

        for (var i = 0; i < lines.Length; i++)
        {
            var line = lines[i];
            var trimmed = line.Trim();

            if (trimmed.Length == 0) continue;

            if (!inTags)
            {
                if (string.Equals(trimmed, "TAGS", StringComparison.Ordinal)) inTags = true;
                continue;
            }

            var match = TagLine.Match(line);
            if (!match.Success)
            {
                // A line inside TAGS that is not a tag is a parse failure, never a skip. A skipped line
                // is a tag silently missing from the view, and an absent row reads as "there is nothing
                // at that register".
                refusals.Add($"line {i + 1} of '{tagTableSource}' is inside the TAGS block and is not a " +
                             $"tag declaration this parser understands: {trimmed}");
                continue;
            }

            var name = match.Groups["name"].Value;
            var type = match.Groups["type"].Value;
            var addr = match.Groups["addr"].Value;

            var placed = Place(addr, baseByte);
            if (placed.Refusal is not null)
            {
                refusals.Add($"line {i + 1} ({name}): {placed.Refusal}");
                continue;
            }

            var mismatch = TypeAgreesWithAddress(type, placed.Width);
            if (mismatch is not null)
            {
                refusals.Add($"line {i + 1} ({name}): {mismatch}");
                continue;
            }

            tags.Add(new MirrorTag(
                name, type, addr, placed.Register, placed.Width, placed.BitInRegister,
                CommentOf(match.Groups["rest"].Value), i + 1));
        }

        if (!inTags)
        {
            return MirrorMapLoad.Refused(
                $"'{tagTableSource}' has no TAGS block, so it is not a tag table this parser can read.");
        }

        if (tags.Count == 0 && refusals.Count == 0)
        {
            // EMPTY IS NOT CLEAN. A tag table that parsed to nothing would render an all-UNMAPPED grid,
            // which looks like a working view of a map that says nothing.
            return MirrorMapLoad.Refused(
                $"'{tagTableSource}' parsed to ZERO tags. An empty map is not a map: every register would " +
                "render as UNMAPPED and the page would look like a working view of a controller that " +
                "names nothing.");
        }

        // ---- 3. THE TWO FILES AGAINST EACH OTHER ----
        foreach (var tag in tags)
        {
            if (tag.LastRegister >= declared)
            {
                refusals.Add($"{tag.Name} ({tag.Address}) lands on register(s) " +
                             $"{tag.Register}..{tag.LastRegister}, outside the {declared} the area pointer " +
                             $"declares (0..{declared - 1}). Either the map or the pointer is stale.");
            }
        }

        foreach (var group in tags.SelectMany(t => Enumerable.Range(t.Register, t.RegisterCount).Select(r => (Register: r, Tag: t)))
                     .GroupBy(x => x.Register)
                     .Where(g => g.Count() > 1))
        {
            refusals.Add($"register {group.Key} is claimed by {group.Count()} tags " +
                         $"({string.Join(", ", group.Select(x => x.Tag.Name).Distinct())}). Overlapping tags " +
                         "mean at least one column on the screen would be decoding somebody else's bytes.");
        }

        foreach (var duplicate in tags.GroupBy(t => t.Name, StringComparer.Ordinal).Where(g => g.Count() > 1))
            refusals.Add($"tag name '{duplicate.Key}' appears {duplicate.Count()} times.");

        return refusals.Count > 0
            ? MirrorMapLoad.Refused(refusals)
            : MirrorMapLoad.Loaded(new MirrorMap(baseByte, declared, tags, tagTableSource, areaPointerSource));
    }

    private readonly record struct Placement(int Register, MirrorWidth Width, int BitInRegister, string? Refusal);

    /// <summary>
    /// Put one <c>%M</c> address on the register grid.
    ///
    /// <para>The inverse of <c>Harness.Map.MirrorGeometry</c>'s three address formatters:
    /// <c>%MD(base+2r)</c>, <c>%MW(base+2r)</c>, and for a bit <c>%M(base+2r+1).k</c> for k&lt;8 or
    /// <c>%M(base+2r).(k-8)</c> for k&gt;=8. Because the base is even, the odd/even parity of a bit
    /// address's byte says unambiguously which of the two forms it is.</para>
    /// </summary>
    private static Placement Place(string address, int baseByte)
    {
        var m = Address.Match(address);
        if (!m.Success)
        {
            return new Placement(0, MirrorWidth.Word, 0,
                $"address '{address}' is not a %M bit-memory address. The mirror lives in %M; an address " +
                "anywhere else is not on the register grid and this parser will not pretend to place it.");
        }

        var kind = m.Groups["kind"].Value;
        var byteAddress = int.Parse(m.Groups["byte"].Value, CultureInfo.InvariantCulture);
        var hasBit = m.Groups["bit"].Success;

        if (byteAddress < baseByte)
        {
            return new Placement(0, MirrorWidth.Word, 0,
                $"address '{address}' is BELOW the mirror base %M{baseByte}, so it is not in the mirrored area.");
        }

        if (kind is "D" or "W")
        {
            if (hasBit)
            {
                return new Placement(0, MirrorWidth.Word, 0,
                    $"address '{address}' names a bit inside a %M{kind} element, which is not an address form " +
                    "the mirror uses.");
            }

            var offset = byteAddress - baseByte;
            if (offset % 2 != 0)
            {
                return new Placement(0, MirrorWidth.Word, 0,
                    $"address '{address}' is at an ODD offset ({offset}) from the base %M{baseByte}, so it " +
                    "straddles two holding registers rather than occupying whole ones.");
            }

            return new Placement(offset / 2, kind == "D" ? MirrorWidth.DoubleWord : MirrorWidth.Word, 0, null);
        }

        if (!hasBit)
        {
            return new Placement(0, MirrorWidth.Word, 0,
                $"address '{address}' is a bare %M byte with no bit. The mirror addresses bit memory as " +
                "%MW/%MD words or as %Mb.n bits; a bare byte is neither.");
        }

        var bit = int.Parse(m.Groups["bit"].Value, CultureInfo.InvariantCulture);
        if (bit is < 0 or > 7)
        {
            return new Placement(0, MirrorWidth.Word, 0,
                $"address '{address}' names bit {bit}; a byte has bits 0..7.");
        }

        var byteOffset = byteAddress - baseByte;
        return byteOffset % 2 == 1
            ? new Placement((byteOffset - 1) / 2, MirrorWidth.Bit, bit, null)     // low byte of the word  -> bits 0..7
            : new Placement(byteOffset / 2, MirrorWidth.Bit, bit + 8, null);      // high byte of the word -> bits 8..15
    }

    /// <summary>
    /// The type name against the address form. Returns the refusal text, or null when they agree.
    ///
    /// <para><b>Unknown type names are ACCEPTED, never accused.</b> The list below is what the mirror
    /// generator emits today; a type it does not carry is something this parser cannot judge, and
    /// declining to judge is the correct verdict when you cannot. The view renders such a tag with its
    /// raw words and says outright that it has no decode for it.</para>
    /// </summary>
    private static string? TypeAgreesWithAddress(string typeName, MirrorWidth width)
    {
        var expected = typeName switch
        {
            "Bool" => (MirrorWidth?)MirrorWidth.Bit,
            "Int" or "UInt" or "Word" => MirrorWidth.Word,
            "DInt" or "UDInt" or "DWord" or "Time" or "Real" => MirrorWidth.DoubleWord,
            _ => null,
        };

        if (expected is null || expected == width) return null;

        return $"type '{typeName}' is a {Describe(expected.Value)} element but its address is a " +
               $"{Describe(width)} one. The address decides how many registers it occupies and the type " +
               "decides how they are read, so a disagreement means the map is wrong in one of two ways and " +
               "picking a winner would hide it.";
    }

    private static string Describe(MirrorWidth width) => width switch
    {
        MirrorWidth.Bit => "single-bit",
        MirrorWidth.Word => "one-register",
        _ => "two-register",
    };

    /// <summary>The COMMENT text, unescaped. Empty when the tag carries none.</summary>
    private static string CommentOf(string rest)
    {
        const string marker = "COMMENT \"";
        var start = rest.IndexOf(marker, StringComparison.Ordinal);
        if (start < 0) return string.Empty;

        var from = start + marker.Length;
        var end = rest.LastIndexOf('"');
        return end <= from ? string.Empty : rest[from..end].Replace("\\\"", "\"", StringComparison.Ordinal);
    }
}
