<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>OpennessCli</RootNamespace>
    <AssemblyName>openness-cli</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Siemens.Engineering">
      <HintPath>$(TiaOpennessDir)\Siemens.Engineering.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

</Project>
