using System.Text.RegularExpressions;
using Harness.Map;

namespace Harness.Map.Tests;

/// <summary>
/// 🔴 <b><see cref="CyclicObGenerator"/> — the block whose ENTIRE CONTENT IS AN ORDER.</b>
///
/// <para>The shape is mechanical and is checked here against the committed <c>Main.ir</c>, which TIA
/// exported and nobody on this lane wrote. <b>The order is not mechanical and the generator originates
/// none of it</b> — so the rest of this file is about what it REFUSES: a declared order that contradicts an
/// ordering its caller derived, and a call list that leaves a generated block unreachable.</para>
///
/// <para>Except where a test reads the corpus, <b>every block name here is INVENTED</b>. A green run of
/// this file is not evidence about any real program.</para>
/// </summary>
public class CyclicObGeneratorTests
{
    private static string IrDirectory
    {
        get
        {
            var dir = new DirectoryInfo(AppContext.BaseDirectory);

            while (dir is not null)
            {
                var candidate = Path.Combine(dir.FullName, "ir", "test-project001");
                if (File.Exists(Path.Combine(candidate, "Main.ir")))
                    return candidate;

                dir = dir.Parent;
            }

            throw new InvalidOperationException(
                "the committed IR corpus was not found by walking up from " + AppContext.BaseDirectory
                + " for ir/test-project001/Main.ir. *** THIS IS A FAILURE, NOT A REASON TO SKIP. ***");
        }
    }

    private static CyclicObNaming Naming(int number = 1, string type = "ProgramCycle") =>
        new("OB_HarnessCycle", number, type, "Harness Program Sweep");

    private static ObCall Call(string block, string? instance, string title) => new(block, instance, title);

    // ---------------------------------------------------------------------------------------------
    // THE SHAPE, AGAINST THE ONE CYCLIC OB TIA HAS EXPORTED HERE
    // ---------------------------------------------------------------------------------------------

    /// <summary>
    /// 🔴 <b>THE COMMITTED <c>Main.ir</c>, DECOMPOSED INTO A CALL LIST AND REGENERATED BYTE FOR BYTE.</b>
    ///
    /// <para>56 hand-typed lines — a header, TIA's two system parameters, and twelve networks — come back
    /// from an ordered list of twelve calls and nothing else. <b>The declaration is read out of the file
    /// rather than typed beside the generator</b>, so this asserts a round trip and not an author's memory
    /// of one.</para>
    /// </summary>
    [Fact]
    public void THE_COMMITTED_CYCLIC_OB_IS_REGENERATED_FROM_ITS_OWN_CALL_LIST()
    {
        var committed = File.ReadAllText(Path.Combine(IrDirectory, "Main.ir")).Replace("\r\n", "\n");

        var result = CyclicObGenerator.Generate(
            new CyclicObNaming("Main", 1, "ProgramCycle", "Main Program Sweep (Cycle)"),
            CallsOf(committed));

        Assert.Equal(committed, result.Ir);
    }

    // ---------------------------------------------------------------------------------------------
    // WHAT IT REFUSES — the order, and the orphan
    // ---------------------------------------------------------------------------------------------

    /// <summary>
    /// 🔴 <b>THE ORPHAN, MECHANISED. A slot FC the OB does not call is REFUSED, and the refusal carries the
    /// generator's own obligation text.</b>
    ///
    /// <para>A hand-written slot FC once sat in a controller called by nothing: every vector timed out and
    /// the start echo reported "commanded, observed to run" throughout, because both halves of that echo
    /// live in the copy layer, which IS called. Until the OB was generated in the same pass, the only
    /// mechanism against it was a sentence.</para>
    /// </summary>
    [Fact]
    public void A_BLOCK_REQUIRED_TO_BE_CALLED_AND_ABSENT_IS_REFUSED()
    {
        var error = Assert.Throws<ArgumentException>(() => CyclicObGenerator.Generate(
            Naming(),
            new[] { Call("FC_HarnessCopyLayer", null, "Copy Layer") },
            new[] { new ObCallPresence("FC_HarnessWidgetSlot", "It would never execute.") }));

        Assert.Contains("does not call 'FC_HarnessWidgetSlot'", error.Message, StringComparison.Ordinal);
        Assert.Contains("It would never execute.", error.Message, StringComparison.Ordinal);
    }

    /// <summary>
    /// 🔴 <b>AND THE ORDER: the slot FC AFTER the copy layer is refused, naming both network numbers.</b>
    ///
    /// <para>Reversed, the copy layer publishes the PREVIOUS scan's observations — which is not a compile
    /// error, not an import error, and shows up as vectors timing out near their backstop.</para>
    /// </summary>
    [Fact]
    public void A_DECLARED_ORDER_THAT_CONTRADICTS_A_DERIVED_ONE_IS_REFUSED()
    {
        var error = Assert.Throws<ArgumentException>(() => CyclicObGenerator.Generate(
            Naming(),
            new[]
            {
                Call("FC_HarnessCopyLayer", null, "Copy Layer"),
                Call("FC_HarnessWidgetSlot", null, "Widget Slot"),
            },
            order: new[] { new ObCallOrder("FC_HarnessWidgetSlot", "FC_HarnessCopyLayer", "The mirror would be a scan behind.") }));

        Assert.Contains("network 2", error.Message, StringComparison.Ordinal);
        Assert.Contains("network 1", error.Message, StringComparison.Ordinal);
        Assert.Contains("The mirror would be a scan behind.", error.Message, StringComparison.Ordinal);
    }

    /// <summary>
    /// 🔴 <b>EMPTY IS NOT CLEAN: an ordering rule whose blocks are not in the call list PASSED BY EXAMINING
    /// NOTHING, so it refuses instead.</b>
    /// </summary>
    [Fact]
    public void AN_ORDERING_RULE_ABOUT_A_BLOCK_THAT_IS_NOT_CALLED_IS_REFUSED()
    {
        var error = Assert.Throws<ArgumentException>(() => CyclicObGenerator.Generate(
            Naming(),
            new[] { Call("FC_HarnessCopyLayer", null, "Copy Layer") },
            order: new[] { new ObCallOrder("FC_Absent", "FC_HarnessCopyLayer", "why") }));

        Assert.Contains("checked against nothing", error.Message, StringComparison.Ordinal);
    }

    /// <summary>An OB number inside the harness band is refused: an OB's number is fixed by its event class.</summary>
    [Fact]
    public void AN_OB_NUMBER_IN_THE_HARNESS_BAND_IS_REFUSED()
    {
        var error = Assert.Throws<ArgumentException>(() => CyclicObGenerator.Generate(
            Naming(number: 9001), new[] { Call("FC_X", null, "X") }));

        Assert.Contains("9000-9999", error.Message, StringComparison.Ordinal);
    }

    /// <summary>
    /// 🔴 <b>ANY EVENT CLASS BUT <c>ProgramCycle</c> IS REFUSED BY NAME.</b> TIA requires an OB's system
    /// parameters to be present and informative and they differ by event class; the corpus grounds one set.
    /// </summary>
    [Fact]
    public void AN_UNGROUNDED_EVENT_CLASS_IS_REFUSED()
    {
        var error = Assert.Throws<ArgumentException>(() => CyclicObGenerator.Generate(
            Naming(type: "Startup"), new[] { Call("FC_X", null, "X") }));

        Assert.Contains("'Startup'", error.Message, StringComparison.Ordinal);
        Assert.Contains("system parameters", error.Message, StringComparison.Ordinal);
    }

    /// <summary>An OB with no calls is a scan that runs no program — and it is what a misspelt key collapses to.</summary>
    [Fact]
    public void AN_OB_WITH_NO_CALLS_IS_REFUSED()
    {
        var error = Assert.Throws<ArgumentException>(() => CyclicObGenerator.Generate(Naming(), Array.Empty<ObCall>()));
        Assert.Contains("declares no calls", error.Message, StringComparison.Ordinal);
    }

    /// <summary>A block called twice in one scan overwrites its own outputs; a copy-pasted network is the way it happens.</summary>
    [Fact]
    public void A_BLOCK_CALLED_TWICE_IS_REFUSED()
    {
        var error = Assert.Throws<ArgumentException>(() => CyclicObGenerator.Generate(
            Naming(),
            new[] { Call("FC_X", null, "First"), Call("FC_X", null, "Second") }));

        Assert.Contains("is called twice", error.Message, StringComparison.Ordinal);
    }

    /// <summary>Two blocks sharing one instance overwrite each other's statics every scan.</summary>
    [Fact]
    public void TWO_CALLS_SHARING_ONE_INSTANCE_ARE_REFUSED()
    {
        var error = Assert.Throws<ArgumentException>(() => CyclicObGenerator.Generate(
            Naming(),
            new[] { Call("FB_A", "iDB_Shared", "A"), Call("FB_B", "iDB_Shared", "B") }));

        Assert.Contains("iDB_Shared", error.Message, StringComparison.Ordinal);
    }

    /// <summary>C-201: every network gets a title, and the generator will not invent one.</summary>
    [Fact]
    public void A_CALL_WITH_NO_NETWORK_TITLE_IS_REFUSED()
    {
        var error = Assert.Throws<ArgumentException>(() => CyclicObGenerator.Generate(
            Naming(), new[] { Call("FC_X", null, "  ") }));

        Assert.Contains("C-201", error.Message, StringComparison.Ordinal);
    }

    /// <summary>An FC has no instance, so its call omits the leading positional argument entirely.</summary>
    [Fact]
    public void AN_FC_CALL_OMITS_THE_INSTANCE_ARGUMENT_AND_AN_FB_CALL_CARRIES_IT()
    {
        var ir = CyclicObGenerator.Generate(
            Naming(),
            new[] { Call("FC_X", null, "Stateless"), Call("FB_Y", "iDB_Y", "Stateful") }).Ir;

        Assert.Contains("CALL FC_X(EN := TRUE)", ir, StringComparison.Ordinal);
        Assert.Contains("CALL FB_Y(iDB_Y, EN := TRUE)", ir, StringComparison.Ordinal);
    }

    // ---------------------------------------------------------------------------------------------
    // helper — the corpus OB read back into the declaration it would be generated from
    // ---------------------------------------------------------------------------------------------

    private static IReadOnlyList<ObCall> CallsOf(string obIr)
    {
        var lines = obIr.Split('\n');
        var calls = new List<ObCall>();
        string? title = null;
        string? comment = null;

        foreach (var line in lines)
        {
            if (line.StartsWith("NETWORK ", StringComparison.Ordinal))
            {
                title = Unescape(line[(line.IndexOf('"') + 1)..^1]);
                comment = null;
                continue;
            }

            if (line.StartsWith("  COMMENT \"", StringComparison.Ordinal))
            {
                comment = Unescape(line["  COMMENT \"".Length..^1]);
                continue;
            }

            var call = Regex.Match(line, @"^  CALL (?<block>\w+)\((?:(?<instance>[\w.]+), )?EN := TRUE\)$");
            if (!call.Success)
                continue;

            calls.Add(new ObCall(
                call.Groups["block"].Value,
                call.Groups["instance"].Success ? call.Groups["instance"].Value : null,
                title ?? throw new InvalidOperationException("a CALL with no NETWORK line before it"),
                comment));
        }

        return calls;
    }

    private static string Unescape(string value) => value.Replace("\\\"", "\"").Replace("\\\\", "\\");
}
