using Harness.Map;

namespace Harness.MirrorView.Tests;

/// <summary>
/// The map comes from the committed artifacts or it does not come at all.
///
/// <para>🔴 <b>THE WHOLE-ARTIFACT SWEEP IS THE POINT OF THE FIRST HALF OF THIS FILE.</b> A hand-written
/// fixture only ever tests the shapes somebody thought of. The real <c>HarnessMirror.ir</c> is sitting
/// in the repository, so the parser is run over it and every one of its 37 maintained registers is
/// required to be accounted for — the input you would otherwise have to guess is already here. The
/// DECLARED window is 1024 and is deliberately wider; that mismatch is asserted, not tolerated.</para>
/// </summary>
public class MirrorMapParserTests
{
    private static string RepoRoot
    {
        get
        {
            var dir = new DirectoryInfo(AppContext.BaseDirectory);
            while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "CLAUDE.md")))
                dir = dir.Parent;

            Assert.True(dir is not null, "could not locate the repository root from " + AppContext.BaseDirectory);
            return dir!.FullName;
        }
    }

    private static string TagTablePath => Path.Combine(RepoRoot, "ir", "test-project001", "HarnessMirror.ir");

    private static string AreaPath => Path.Combine(RepoRoot, "ir", "test-project001", "FB_Comms_ModbusServer.ir");

    private static MirrorMap RealMap()
    {
        var load = MirrorMapParser.Load(TagTablePath, AreaPath);
        Assert.True(load.Ok, "the committed artifacts did not parse: " + string.Join(" | ", load.Refusals));
        return load.Map!;
    }

    // ---- 1. THE COMMITTED ARTIFACTS ---------------------------------------------------------------

    [Fact]
    public void TheCommittedArtifacts_ParseIntoAWholeMap()
    {
        var map = RealMap();

        Assert.Equal(1000, map.BaseByte);
        Assert.Equal(1024, map.DeclaredRegisters);
        Assert.Equal(26, map.Tags.Count);
    }

    /// <summary>
    /// The maintained mirror is 37 contiguous registers inside a declared window of 1024, and the 987
    /// registers between them are unmapped ON PURPOSE.
    ///
    /// <para>🔴 <b>THIS TEST USED TO ASSERT THAT EVERY DECLARED REGISTER WAS NAMED BY A TAG, AND THAT
    /// INVARIANT WAS DELIBERATELY RETIRED.</b> Its wording was: "an unmapped register is a row the page
    /// must render as UNMAPPED, and the day one appears it should be a decision somebody made rather
    /// than a surprise on the screen." That day came, and it WAS a decision somebody made — the
    /// committed comms block says so itself: <i>"deliberately wider than the mirror the copy layer
    /// currently maintains… a register past the maintained mirror now reads as zero instead of
    /// returning an exception"</i>. The window was widened to 1024 so one mirror can carry several
    /// conformance slots in a single wave, and the exact-fit guard was the stated cost.</para>
    ///
    /// <para>So the gap is asserted rather than tolerated. A drift in the MAINTAINED mirror — a tag
    /// added, dropped, resized or overlapped — still fails here, and a change to the declared window
    /// fails too, which is the point: both halves of a deliberate mismatch are now written down.</para>
    /// </summary>
    [Fact]
    public void TheMaintainedMirrorIsContiguousAndDeliberatelyNarrowerThanTheDeclaredWindow()
    {
        var map = RealMap();

        var covered = map.Tags.SelectMany(t => Enumerable.Range(t.Register, t.RegisterCount)).ToList();
        Assert.Equal(37, covered.Count);
        Assert.Equal(37, covered.Distinct().Count());          // no two tags overlap
        Assert.Equal(0, covered.Min());
        Assert.Equal(36, covered.Max());                       // contiguous 0..36, no hole inside it

        Assert.Equal(1024, map.DeclaredRegisters);
        Assert.Equal(987, map.UnmappedRegisters.Count);        // 1024 - 37, every one above the mirror
        Assert.Equal(37, map.UnmappedRegisters.Min());
    }

    /// <summary>
    /// *** THE OUTSIDE AUTHORITY. *** This parser inverts <c>Harness.Map.MirrorGeometry</c>'s address
    /// formatters — the very class the copy layer's addresses were GENERATED by. Round-tripping every
    /// real tag through it is a check against something that is not this file's own belief; a test that
    /// only re-derived the arithmetic here would demonstrate self-consistency and nothing else.
    /// </summary>
    [Fact]
    public void EveryTag_RoundTripsThroughMirrorGeometry()
    {
        var map = RealMap();
        var geometry = MirrorGeometry.ForCpu1214C(retentiveBytes: 0, baseByte: map.BaseByte, declaredRegisters: (MirrorGeometry.Cpu1214CBitMemoryBytes - map.BaseByte) / 2);

        Assert.NotEmpty(map.Tags);

        foreach (var tag in map.Tags)
        {
            var rebuilt = tag.Width switch
            {
                MirrorWidth.Bit => geometry.BitAddressOf(tag.Register, tag.BitInRegister),
                MirrorWidth.Word => geometry.WordAddressOf(tag.Register),
                _ => geometry.DoubleWordAddressOf(tag.Register),
            };

            Assert.True(rebuilt == tag.Address,
                $"{tag.Name}: parsed to register {tag.Register} (bit {tag.BitInRegister}), which " +
                $"MirrorGeometry formats as {rebuilt} — the artifact says {tag.Address}.");
        }
    }

    /// <summary>The three placements the brief names, checked against the real tags that carry them.</summary>
    [Theory]
    [InlineData("HX_ProgramVersion", 0, 2, "%MD1000")]
    [InlineData("HX_ScanCount", 2, 2, "%MD1004")]
    [InlineData("HX_HBA_Start", 4, 1, "%M1009.0")]
    [InlineData("HX_HBA_V000", 6, 1, "%MW1012")]
    [InlineData("HX_HBA_V003", 9, 2, "%MD1018")]
    [InlineData("HX_HBA_L008", 35, 1, "%M1071.0")]
    [InlineData("HX_HBA_L009", 36, 1, "%M1073.0")]
    public void KnownTags_LandOnTheRegistersTheirOwnCommentsName(string name, int register, int count, string address)
    {
        var tag = RealMap().Tags.Single(t => t.Name == name);

        Assert.Equal(register, tag.Register);
        Assert.Equal(count, tag.RegisterCount);
        Assert.Equal(address, tag.Address);
    }

    /// <summary>
    /// The comment column is the "meaning" column, and it must arrive intact — the latch tags' comments
    /// are the only place the phase-arming rule is written down where a reader of the page can see it.
    /// </summary>
    [Fact]
    public void TheCommentText_ArrivesFromTheArtifact()
    {
        var latch = RealMap().Tags.Single(t => t.Name == "HX_HBA_L008");

        Assert.Contains("PHASE-ARMED", latch.Comment, StringComparison.Ordinal);
        Assert.Contains("HopperBlockedAlarm", latch.Comment, StringComparison.Ordinal);
        Assert.DoesNotContain("COMMENT", latch.Comment, StringComparison.Ordinal);
    }

    // ---- 2. THE REFUSALS ---------------------------------------------------------------------------

    private const string Area = "  MB_SERVER(MbServer, MB_HOLD_REG := P#M1000.0 WORD 4, CONNECT := Comms)";

    private static MirrorMapLoad ParseTags(string tags, string area = Area) =>
        MirrorMapParser.Parse(tags, area, "tags.ir", "area.ir");

    [Fact]
    public void NoAreaPointer_IsARefusal_NotADefaultBase()
    {
        var load = ParseTags("TAGS\n  A 1 : Int @ %MW1000\n", area: "MB_SERVER(MbServer, CONNECT := Comms)");

        Assert.False(load.Ok);
        Assert.Contains(load.Refusals, r => r.Contains("MB_HOLD_REG", StringComparison.Ordinal));
    }

    [Fact]
    public void TwoDifferentAreaPointers_AreARefusal_RatherThanTakingTheFirst()
    {
        var load = ParseTags("TAGS\n  A 1 : Int @ %MW1000\n",
            area: "P#M1000.0 WORD 37\nP#M2000.0 WORD 12\n");

        Assert.False(load.Ok);
        Assert.Contains(load.Refusals, r => r.Contains("DIFFERENT area pointers", StringComparison.Ordinal));
    }

    [Fact]
    public void ATagOutsideTheDeclaredArea_IsARefusal()
    {
        var load = ParseTags("TAGS\n  A 1 : Int @ %MW1008\n");

        Assert.False(load.Ok);
        Assert.Contains(load.Refusals, r => r.Contains("outside the 4", StringComparison.Ordinal));
    }

    [Fact]
    public void OverlappingTags_AreARefusal()
    {
        var load = ParseTags("TAGS\n  A 1 : DWord @ %MD1000\n  B 2 : Int @ %MW1002\n");

        Assert.False(load.Ok);
        Assert.Contains(load.Refusals, r => r.Contains("claimed by 2 tags", StringComparison.Ordinal));
    }

    /// <summary>
    /// A type and an address that disagree is refused rather than resolved. Picking a winner would put a
    /// decoded column on the screen against somebody else's bytes, and the screen would look fine.
    /// </summary>
    [Fact]
    public void ATypeThatDisagreesWithItsAddress_IsARefusal()
    {
        var load = ParseTags("TAGS\n  A 1 : Time @ %MW1000\n");

        Assert.False(load.Ok);
        Assert.Contains(load.Refusals, r => r.Contains("two-register", StringComparison.Ordinal));
    }

    /// <summary>An unreadable line inside TAGS is a refusal, never a skip: a skipped tag is a silent hole.</summary>
    [Fact]
    public void AnUnreadableLineInsideTags_IsARefusal_NotASkip()
    {
        var load = ParseTags("TAGS\n  A 1 : Int @ %MW1000\n  this is not a tag\n");

        Assert.False(load.Ok);
        Assert.Contains(load.Refusals, r => r.Contains("not a tag declaration", StringComparison.Ordinal));
    }

    [Fact]
    public void NoTagsBlockAtAll_IsARefusal()
    {
        var load = ParseTags("TAGTABLE HarnessMirror\n  ROOTID 0\n");

        Assert.False(load.Ok);
        Assert.Contains(load.Refusals, r => r.Contains("no TAGS block", StringComparison.Ordinal));
    }

    /// <summary>EMPTY IS NOT CLEAN. A tag table that parsed to nothing renders a whole grid of UNMAPPED.</summary>
    [Fact]
    public void AnEmptyTagsBlock_IsARefusal()
    {
        var load = ParseTags("TAGS\n");

        Assert.False(load.Ok);
        Assert.Contains(load.Refusals, r => r.Contains("ZERO tags", StringComparison.Ordinal));
    }

    [Fact]
    public void AnAddressOutsideBitMemory_IsARefusal()
    {
        var load = ParseTags("TAGS\n  A 1 : Int @ %IW100\n");

        Assert.False(load.Ok);
        Assert.Contains(load.Refusals, r => r.Contains("not a %M bit-memory address", StringComparison.Ordinal));
    }

    [Fact]
    public void AMissingFile_IsARefusal_WithNoFallbackMap()
    {
        var load = MirrorMapParser.Load(Path.Combine(Path.GetTempPath(), "no-such-mirror.ir"), AreaPath);

        Assert.False(load.Ok);
        Assert.Null(load.Map);
        Assert.NotEmpty(load.Refusals);
    }

    /// <summary>
    /// A type this parser has no width rule for is ACCEPTED on the strength of its address, never
    /// accused. Declining to judge is the correct verdict when you cannot; the page then says outright
    /// that it has no decode for it.
    /// </summary>
    [Fact]
    public void AnUnknownTypeName_IsPlacedByItsAddress_AndNotRefused()
    {
        var load = ParseTags("TAGS\n  A 1 : LWord @ %MW1000\n");

        Assert.True(load.Ok, string.Join(" | ", load.Refusals));
        Assert.Equal(MirrorWidth.Word, load.Map!.Tags.Single().Width);
    }
}
